# Generated by Django 3.0.10 on 2021-04-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=250)),
                ('phone', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
